package nick.games.sudoku;

import static nick.games.sudoku.api.Number.*;

import io.vavr.collection.List;
import nick.games.sudoku.api.Number;


public final class TestData {
  public static final List<Number[][]> easyGames = List.of(new Number[][][]{
      new Number[][] {
          {THREE, SEVEN, NINE, null, null, null, null, ONE, FOUR},
          {null, SIX, null, null, ONE, null, null, SEVEN, null},
          {null, EIGHT, null, null, null, NINE, null, null, FIVE},
          {FOUR, THREE, FIVE, null, null, SEVEN, null, null, null},
          {null, NINE, null, null, FOUR, null, null, TWO, null},
          {null, null, null, EIGHT, null, null, FOUR, THREE, SIX},
          {NINE, null, null, SEVEN, null, null, null, EIGHT, null},
          {null, FOUR, null, null, EIGHT, null, null, FIVE, null},
          {EIGHT, FIVE, null, null, null, null, TWO, FOUR, NINE},
      },
      new Number[][] {
          {null, SEVEN, null, null, null, null, EIGHT, ONE, null},
          {null, null, null, THREE, ONE, EIGHT, NINE, null, TWO},
          {TWO, EIGHT, ONE, FOUR, SEVEN, null, null, null, FIVE},
          {FOUR, null, null, null, SIX, null, null, null, null},
          {SIX, NINE, null, ONE, null, THREE, null, TWO, SEVEN},
          {null, null, null, null, NINE, null, null, null, SIX},
          {NINE, null, null, null, FIVE, FOUR, SIX, EIGHT, ONE},
          {ONE, null, SIX, NINE, EIGHT, TWO, null, null, null},
          {null, FIVE, SEVEN, null, null, null, null, FOUR, null},
      },
      new Number[][] {
          {null, null, null, null, TWO, null, null, ONE, null},
          {FIVE, null, FOUR, null, ONE, EIGHT, NINE, SEVEN, TWO},
          {null, EIGHT, null, FOUR, null, NINE, null, null, FIVE},
          {null, null, null, null, null, null, ONE, null, EIGHT},
          {SIX, NINE, null, ONE, null, THREE, null, TWO, SEVEN},
          {SEVEN, null, TWO, null, null, null, null, null, null},
          {NINE, null, null, SEVEN, null, FOUR, null, EIGHT, null},
          {ONE, FOUR, SIX, NINE, EIGHT, null, SEVEN, null, THREE},
          {null, FIVE, null, null, THREE, null, null, null, null},
      },
      new Number[][] {
          {null, EIGHT, null, null, null, TWO, ONE, SIX, null},
          {null, null, null, null, SEVEN, SIX, TWO, null, null},
          {SIX, null, FIVE, null, null, EIGHT, null, null, null},
          {null, null, SIX, null, null, ONE, null, THREE, EIGHT},
          {null, FOUR, null, null, THREE, null, null, NINE, null},
          {EIGHT, FIVE, null, SIX, null, null, SEVEN, null, null},
          {null, null, null, SEVEN, null, null, THREE, null, NINE},
          {null, null, TWO, FOUR, SIX, null, null, null, null},
          {null, THREE, SEVEN, ONE, null, null, null, FIVE, null},
      },
      new Number[][] {
          {null, null, NINE, null, null, TWO, null, SIX, null},
          {null, null, FOUR, null, null, null, TWO, null, null},
          {null, TWO, null, THREE, ONE, EIGHT, NINE, SEVEN, null},
          {null, SEVEN, SIX, null, FIVE, null, FOUR, null, null},
          {TWO, FOUR, null, null, THREE, null, null, NINE, SIX},
          {null, null, THREE, null, NINE, null, SEVEN, TWO, null},
          {null, SIX, EIGHT, SEVEN, TWO, FIVE, null, FOUR, null},
          {null, null, TWO, null, null, null, EIGHT, null, null},
          {null, THREE, null, ONE, null, null, SIX, null, null},
      },
      new Number[][] {
          {null, EIGHT, NINE, null, null, TWO, null, SIX, THREE},
          {null, null, FOUR, null, SEVEN, SIX, TWO, null, FIVE},
          {null, null, null, THREE, null, EIGHT, NINE, null, FOUR},
          {null, null, null, TWO, null, null, FOUR, null, EIGHT},
          {TWO, null, null, null, THREE, null, null, null, SIX},
          {EIGHT, null, THREE, null, null, FOUR, null, null, null},
          {ONE, null, EIGHT, SEVEN, null, FIVE, null, null, null},
          {FIVE, null, TWO, FOUR, SIX, null, EIGHT, null, null},
          {FOUR, THREE, null, ONE, null, null, SIX, FIVE, null},
      },
      new Number[][] {
          {SEVEN, EIGHT, null, FIVE, null, TWO, null, SIX, null},
          {null, null, null, null, SEVEN, null, null, null, FIVE},
          {null, TWO, null, THREE, ONE, null, NINE, SEVEN, null},
          {NINE, null, null, TWO, FIVE, ONE, FOUR, THREE, null},
          {null, FOUR, ONE, EIGHT, null, SEVEN, FIVE, NINE, null},
          {null, FIVE, THREE, SIX, NINE, FOUR, null, null, ONE},
          {null, SIX, EIGHT, null, TWO, FIVE, null, FOUR, null},
          {FIVE, null, null, null, SIX, null, null, null, null},
          {null, THREE, null, ONE, null, NINE, null, FIVE, TWO},
      },
      new Number[][] {
          {null, EIGHT, null, FIVE, FOUR, null, ONE, SIX, null},
          {null, null, null, NINE, null, null, TWO, null, FIVE},
          {SIX, TWO, null, THREE, null, null, null, SEVEN, null},
          {NINE, null, null, null, FIVE, null, null, THREE, EIGHT},
          {null, FOUR, null, EIGHT, null, SEVEN, null, NINE, null},
          {EIGHT, FIVE, null, null, NINE, null, null, null, ONE},
          {null, SIX, null, null, null, FIVE, null, FOUR, NINE},
          {FIVE, null, TWO, null, null, THREE, null, null, null},
          {null, THREE, SEVEN, null, EIGHT, NINE, null, FIVE, null},
      },
      new Number[][] {
          {null, SIX, TWO, ONE, null, null, FOUR, EIGHT, null},
          {FOUR, null, THREE, null, EIGHT, null, null, NINE, SEVEN},
          {null, null, NINE, null, SEVEN, null, ONE, TWO, null},
          {FIVE, null, null, null, NINE, null, null, SEVEN, null},
          {TWO, null, null, EIGHT, null, FOUR, null, null, NINE},
          {null, NINE, null, null, TWO, null, null, null, ONE},
          {null, SEVEN, FIVE, null, THREE, null, EIGHT, null, null},
          {ONE, TWO, null, null, FOUR, null, NINE, null, FIVE},
          {null, EIGHT, FOUR, null, null, FIVE, SEVEN, ONE, null},
      },
      new Number[][] {
          {null, SIX, TWO, null, FIVE, null, FOUR, null, THREE},
          {null, null, THREE, SIX, null, TWO, FIVE, null, SEVEN},
          {null, null, null, FOUR, null, null, null, null, SIX},
          {FIVE, null, null, null, NINE, SIX, TWO, null, null},
          {null, THREE, null, EIGHT, null, FOUR, null, FIVE, null},
          {null, null, EIGHT, FIVE, TWO, null, null, null, ONE},
          {NINE, null, null, null, null, ONE, null, null, null},
          {ONE, null, SIX, SEVEN, null, EIGHT, NINE, null, null},
          {THREE, null, FOUR, null, SIX, null, SEVEN, ONE, null},
      },
      new Number[][] {
          {SEVEN, null, null, ONE, FIVE, null, null, null, null},
          {null, null, THREE, null, null, TWO, null, NINE, SEVEN},
          {EIGHT, null, null, FOUR, SEVEN, null, ONE, TWO, SIX},
          {FIVE, null, null, THREE, NINE, null, TWO, null, null},
          {null, THREE, null, null, ONE, null, null, FIVE, null},
          {null, null, EIGHT, null, TWO, SEVEN, null, null, ONE},
          {NINE, SEVEN, FIVE, null, THREE, ONE, null, null, FOUR},
          {ONE, TWO, null, SEVEN, null, null, NINE, null, null},
          {null, null, null, null, SIX, FIVE, null, null, TWO},
      },
      new Number[][] {
          {null, null, TWO, null, null, NINE, FOUR, EIGHT, THREE},
          {null, null, null, SIX, EIGHT, null, null, null, null},
          {EIGHT, null, null, FOUR, null, THREE, ONE, null, null},
          {FIVE, FOUR, null, null, NINE, null, null, SEVEN, EIGHT},
          {null, THREE, null, EIGHT, null, FOUR, null, FIVE, null},
          {SIX, NINE, null, null, TWO, null, null, FOUR, ONE},
          {null, null, FIVE, TWO, null, ONE, null, null, FOUR},
          {null, null, null, null, FOUR, EIGHT, null, null, null},
          {THREE, EIGHT, FOUR, NINE, null, null, SEVEN, null, null},
      },
      new Number[][] {
          {NINE, null, FOUR, null, null, null, null, null, null},
          {FIVE, null, null, FOUR, THREE, null, ONE, SEVEN, EIGHT},
          {THREE, SEVEN, null, ONE, null, SIX, null, TWO, FOUR},
          {SIX, null, null, null, SEVEN, null, FOUR, THREE, null},
          {null, FOUR, SEVEN, null, null, null, EIGHT, NINE, null},
          {null, THREE, ONE, null, NINE, null, null, null, SEVEN},
          {SEVEN, EIGHT, null, FIVE, null, THREE, null, ONE, NINE},
          {FOUR, NINE, FIVE, null, SIX, ONE, null, null, THREE},
          {null, null, null, null, null, null, FIVE, null, TWO},
      },
      new Number[][] {
          {null, ONE, FOUR, null, null, EIGHT, THREE, SIX, null},
          {null, null, SIX, null, THREE, null, ONE, null, EIGHT},
          {null, SEVEN, EIGHT, ONE, null, null, NINE, null, FOUR},
          {null, null, null, EIGHT, null, TWO, null, THREE, ONE},
          {null, FOUR, SEVEN, THREE, ONE, FIVE, EIGHT, NINE, null},
          {EIGHT, THREE, null, SIX, null, FOUR, null, null, null},
          {SEVEN, null, TWO, null, null, THREE, SIX, ONE, null},
          {FOUR, null, FIVE, null, SIX, null, SEVEN, null, null},
          {null, SIX, THREE, NINE, null, null, FIVE, FOUR, null},
      },
      new Number[][] {
          {null, ONE, FOUR, SEVEN, null, EIGHT, THREE, null, null},
          {null, null, null, null, THREE, NINE, ONE, SEVEN, null},
          {THREE, SEVEN, null, null, null, SIX, null, null, FOUR},
          {null, null, NINE, null, null, TWO, null, THREE, ONE},
          {null, FOUR, null, null, null, null, null, NINE, null},
          {EIGHT, THREE, null, SIX, null, null, TWO, null, null},
          {SEVEN, null, null, FIVE, null, null, null, ONE, NINE},
          {null, NINE, FIVE, TWO, SIX, null, null, null, null},
          {null, null, THREE, NINE, null, SEVEN, FIVE, FOUR, null},
      },
      new Number[][] {
          {null, TWO, EIGHT, NINE, null, null, SEVEN, null, ONE},
          {FIVE, null, null, SIX, null, null, EIGHT, null, null},
          {THREE, null, null, null, ONE, null, null, TWO, NINE},
          {null, EIGHT, null, null, null, ONE, null, THREE, null},
          {null, SIX, null, SEVEN, null, NINE, null, ONE, null},
          {null, FOUR, null, THREE, null, null, null, NINE, null},
          {SEVEN, NINE, null, null, FIVE, null, null, null, FOUR},
          {null, null, SIX, null, null, THREE, null, null, TWO},
          {EIGHT, null, TWO, null, null, SIX, ONE, SEVEN, null},
      },
      new Number[][] {
          {SIX, null, null, NINE, null, FOUR, SEVEN, FIVE, null},
          {FIVE, null, NINE, SIX, TWO, null, null, null, null},
          {THREE, null, null, FIVE, null, EIGHT, null, TWO, null},
          {null, null, null, null, null, ONE, FOUR, THREE, null},
          {null, SIX, null, SEVEN, null, NINE, null, ONE, null},
          {null, FOUR, SEVEN, THREE, null, null, null, null, null},
          {null, NINE, null, EIGHT, null, TWO, null, null, FOUR},
          {null, null, null, null, SEVEN, THREE, NINE, null, TWO},
          {null, THREE, TWO, FOUR, null, SIX, null, null, FIVE},
      },
      new Number[][] {
          {SIX, TWO, null, NINE, null, FOUR, SEVEN, null, null},
          {null, null, NINE, SIX, null, SEVEN, EIGHT, null, THREE},
          {null, null, null, FIVE, null, null, null, null, NINE},
          {null, null, null, null, null, ONE, null, THREE, null},
          {TWO, SIX, null, SEVEN, FOUR, NINE, null, ONE, EIGHT},
          {null, FOUR, null, THREE, null, null, null, null, null},
          {SEVEN, null, null, null, null, TWO, null, null, null},
          {FOUR, null, SIX, ONE, null, THREE, NINE, null, null},
          {null, null, TWO, FOUR, null, SIX, null, SEVEN, FIVE},
      },
      new Number[][] {
          {NINE, null, null, THREE, null, FIVE, null, FOUR, null},
          {null, TWO, null, null, null, null, THREE, null, EIGHT},
          {null, THREE, null, null, FOUR, TWO, ONE, SEVEN, null},
          {null, FOUR, ONE, null, null, SIX, null, null, null},
          {null, NINE, FIVE, ONE, null, THREE, FOUR, SIX, null},
          {null, null, null, FOUR, null, null, TWO, ONE, null},
          {null, ONE, THREE, NINE, SEVEN, null, null, TWO, null},
          {EIGHT, null, TWO, null, null, null, null, NINE, null},
          {null, SEVEN, null, FIVE, null, FOUR, null, null, ONE},
      },
      new Number[][] {
          {null, null, null, null, null, FIVE, null, null, null},
          {ONE, null, null, null, SIX, null, THREE, FIVE, EIGHT},
          {FIVE, THREE, null, null, FOUR, TWO, null, null, NINE},
          {SEVEN, null, ONE, null, null, null, null, EIGHT, null},
          {TWO, NINE, FIVE, null, EIGHT, null, FOUR, SIX, SEVEN},
          {null, SIX, null, null, null, null, TWO, null, FIVE},
          {FOUR, null, null, NINE, SEVEN, null, null, TWO, SIX},
          {EIGHT, FIVE, TWO, null, THREE, null, null, null, FOUR},
          {null, null, null, FIVE, null, null, null, null, null},
      },
      new Number[][] {
          {null, EIGHT, null, THREE, null, FIVE, SIX, FOUR, null},
          {null, null, null, SEVEN, null, null, null, FIVE, null},
          {FIVE, null, null, EIGHT, FOUR, TWO, ONE, null, null},
          {SEVEN, null, ONE, null, null, null, NINE, null, null},
          {TWO, NINE, null, null, null, null, null, SIX, SEVEN},
          {null, null, EIGHT, null, null, null, TWO, null, FIVE},
          {null, null, THREE, NINE, SEVEN, EIGHT, null, null, SIX},
          {null, FIVE, null, null, null, ONE, null, null, null},
          {null, SEVEN, NINE, FIVE, null, FOUR, null, THREE, null},
      },
      new Number[][] {
          {null, null, null, null, null, FIVE, null, FOUR, null},
          {ONE, null, FOUR, SEVEN, null, null, THREE, null, EIGHT},
          {null, THREE, SIX, null, null, TWO, null, null, NINE},
          {null, null, ONE, null, null, SIX, NINE, EIGHT, THREE},
          {null, null, null, ONE, null, THREE, null, null, null},
          {THREE, SIX, EIGHT, FOUR, null, null, TWO, null, null},
          {FOUR, null, null, NINE, null, null, FIVE, TWO, null},
          {EIGHT, null, TWO, null, null, ONE, SEVEN, null, FOUR},
          {null, SEVEN, null, FIVE, null, null, null, null, null},
      },
      new Number[][] {
          {null, null, THREE, EIGHT, null, ONE, null, null, null},
          {null, SEVEN, EIGHT, null, SIX, null, null, ONE, null},
          {SIX, null, FOUR, null, null, SEVEN, NINE, null, TWO},
          {null, FOUR, ONE, TWO, NINE, THREE, FIVE, SEVEN, null},
          {null, null, null, null, null, null, null, null, null},
          {null, FIVE, TWO, FOUR, ONE, SIX, EIGHT, NINE, null},
          {FOUR, null, FIVE, SIX, null, null, ONE, null, EIGHT},
          {null, EIGHT, null, null, FOUR, null, TWO, SIX, null},
          {null, null, null, THREE, null, TWO, SEVEN, null, null},
      },
      new Number[][] {
          {null, NINE, THREE, null, null, null, SIX, null, SEVEN},
          {TWO, SEVEN, null, NINE, null, FOUR, THREE, null, null},
          {null, null, null, null, null, null, null, null, TWO},
          {null, null, ONE, null, NINE, THREE, null, SEVEN, null},
          {null, null, SIX, SEVEN, FIVE, EIGHT, FOUR, null, null},
          {null, FIVE, null, FOUR, ONE, null, EIGHT, null, null},
          {FOUR, null, null, null, null, null, null, null, null},
          {null, null, SEVEN, ONE, null, FIVE, null, SIX, NINE},
          {ONE, null, NINE, null, null, null, SEVEN, FIVE, null},
      },
      new Number[][] {
          {FIVE, NINE, null, EIGHT, TWO, null, SIX, null, null},
          {TWO, null, null, null, null, FOUR, THREE, null, null},
          {null, ONE, FOUR, FIVE, null, SEVEN, NINE, null, null},
          {EIGHT, null, null, TWO, NINE, null, null, null, null},
          {NINE, null, SIX, SEVEN, null, EIGHT, FOUR, null, ONE},
          {null, null, null, null, ONE, SIX, null, null, THREE},
          {null, null, FIVE, SIX, null, NINE, ONE, THREE, null},
          {null, null, SEVEN, ONE, null, null, null, null, NINE},
          {null, null, NINE, null, EIGHT, TWO, null, FIVE, FOUR},
      },
      new Number[][] {
          {null, null, null, EIGHT, TWO, null, null, FOUR, null},
          {TWO, null, null, NINE, null, FOUR, THREE, ONE, null},
          {null, ONE, null, FIVE, null, null, NINE, EIGHT, null},
          {EIGHT, null, ONE, null, null, null, null, SEVEN, SIX},
          {null, null, SIX, SEVEN, FIVE, EIGHT, FOUR, null, null},
          {SEVEN, FIVE, null, null, null, null, EIGHT, null, THREE},
          {null, TWO, FIVE, null, null, NINE, null, THREE, null},
          {null, EIGHT, SEVEN, ONE, null, FIVE, null, null, NINE},
          {null, SIX, null, null, EIGHT, TWO, null, null, null},
      },
      new Number[][] {
          {null, SEVEN, FOUR, null, FIVE, null, TWO, null, null},
          {NINE, null, FIVE, null, TWO, FOUR, null, null, null},
          {null, THREE, null, SEVEN, null, null, null, FIVE, null},
          {TWO, ONE, NINE, FIVE, THREE, null, null, null, null},
          {null, null, EIGHT, null, SEVEN, null, THREE, null, null},
          {null, null, null, null, SIX, TWO, EIGHT, NINE, ONE},
          {null, NINE, null, null, null, FIVE, null, ONE, null},
          {null, null, null, THREE, FOUR, null, NINE, null, SIX},
          {null, null, SEVEN, null, NINE, null, FIVE, FOUR, null},
      },
      new Number[][] {
          {null, null, null, NINE, null, null, null, SIX, null},
          {NINE, SIX, null, null, TWO, FOUR, ONE, THREE, null},
          {EIGHT, THREE, TWO, null, ONE, null, FOUR, null, null},
          {null, null, null, null, null, EIGHT, SIX, null, FOUR},
          {SIX, FOUR, null, null, null, null, null, TWO, FIVE},
          {SEVEN, null, THREE, FOUR, null, null, null, null, null},
          {null, null, SIX, null, EIGHT, null, SEVEN, ONE, THREE},
          {null, TWO, ONE, THREE, FOUR, null, null, EIGHT, SIX},
          {null, EIGHT, null, null, null, ONE, null, null, null},
      },
      new Number[][] {
          {null, null, null, NINE, FIVE, null, TWO, null, null},
          {null, SIX, FIVE, null, null, null, ONE, null, SEVEN},
          {EIGHT, null, null, SEVEN, null, SIX, FOUR, null, NINE},
          {TWO, ONE, null, null, null, null, SIX, null, null},
          {SIX, null, null, ONE, SEVEN, NINE, null, null, FIVE},
          {null, null, THREE, null, null, null, null, NINE, ONE},
          {FOUR, null, SIX, TWO, null, FIVE, null, null, THREE},
          {FIVE, null, ONE, null, null, null, NINE, EIGHT, null},
          {null, null, SEVEN, null, NINE, ONE, null, null, null},
      },
      new Number[][] {
          {ONE, null, SIX, NINE, null, FIVE, null, THREE, TWO},
          {NINE, null, FIVE, null, null, SIX, SEVEN, null, null},
          {null, EIGHT, null, ONE, SEVEN, null, FIVE, null, null},
          {null, THREE, null, null, null, ONE, FOUR, null, FIVE},
          {EIGHT, SIX, null, null, FIVE, null, null, ONE, NINE},
          {TWO, null, ONE, FOUR, null, null, null, SIX, null},
          {null, null, SEVEN, null, SIX, FOUR, null, FIVE, null},
          {null, null, EIGHT, THREE, null, null, SIX, null, FOUR},
          {SIX, FOUR, null, FIVE, null, NINE, ONE, null, THREE},
      },
      new Number[][] {
          {ONE, null, null, null, null, FIVE, EIGHT, THREE, null},
          {NINE, null, FIVE, EIGHT, null, SIX, SEVEN, null, ONE},
          {null, EIGHT, null, ONE, null, TWO, null, null, SIX},
          {null, null, null, null, TWO, ONE, FOUR, null, null},
          {null, null, FOUR, null, null, null, TWO, null, null},
          {null, null, ONE, FOUR, NINE, null, null, null, null},
          {THREE, null, null, TWO, null, FOUR, null, FIVE, null},
          {FIVE, null, EIGHT, THREE, null, SEVEN, SIX, null, FOUR},
          {null, FOUR, TWO, FIVE, null, null, null, null, THREE},
      },
      new Number[][] {
          {ONE, null, SIX, NINE, null, null, null, null, null},
          {NINE, null, FIVE, null, null, null, SEVEN, FOUR, null},
          {null, EIGHT, null, ONE, SEVEN, null, FIVE, null, null},
          {null, null, NINE, null, null, ONE, null, EIGHT, null},
          {null, SIX, FOUR, SEVEN, FIVE, THREE, TWO, ONE, null},
          {null, FIVE, null, FOUR, null, null, THREE, null, null},
          {null, null, SEVEN, null, SIX, FOUR, null, FIVE, null},
          {null, NINE, EIGHT, null, null, null, SIX, null, FOUR},
          {null, null, null, null, null, NINE, ONE, null, THREE},
      },
      new Number[][] {
          {null, SEVEN, null, NINE, FOUR, null, null, null, null},
          {NINE, null, FIVE, null, null, null, null, FOUR, ONE},
          {null, EIGHT, THREE, ONE, SEVEN, null, FIVE, null, null},
          {SEVEN, THREE, null, null, TWO, null, FOUR, null, FIVE},
          {EIGHT, null, FOUR, SEVEN, null, THREE, TWO, null, NINE},
          {TWO, null, ONE, null, NINE, null, null, SIX, SEVEN},
          {null, null, SEVEN, null, SIX, FOUR, NINE, FIVE, null},
          {FIVE, NINE, null, null, null, null, SIX, null, FOUR},
          {null, null, null, null, EIGHT, NINE, null, SEVEN, null},
      },
      new Number[][] {
          {null, null, THREE, SIX, NINE, null, null, null, null},
          {null, ONE, FIVE, SEVEN, EIGHT, null, null, null, FOUR},
          {SEVEN, null, SIX, null, TWO, FIVE, NINE, null, null},
          {null, null, null, EIGHT, null, null, null, NINE, FIVE},
          {FIVE, FOUR, ONE, NINE, null, SIX, SEVEN, EIGHT, TWO},
          {THREE, NINE, null, null, null, SEVEN, null, null, null},
          {null, null, SEVEN, ONE, FOUR, null, SIX, null, NINE},
          {ONE, null, null, null, SIX, NINE, EIGHT, TWO, null},
          {null, null, null, null, SEVEN, EIGHT, ONE, null, null},
      },
      new Number[][] {
          {null, TWO, THREE, null, null, null, FIVE, null, null},
          {NINE, ONE, FIVE, SEVEN, EIGHT, null, null, null, null},
          {null, EIGHT, null, FOUR, TWO, null, null, THREE, null},
          {null, null, TWO, EIGHT, null, null, null, null, FIVE},
          {FIVE, FOUR, null, NINE, null, SIX, null, EIGHT, TWO},
          {THREE, null, null, null, null, SEVEN, FOUR, null, null},
          {null, THREE, null, null, FOUR, TWO, null, FIVE, null},
          {null, null, null, null, SIX, NINE, EIGHT, TWO, SEVEN},
          {null, null, NINE, null, null, null, ONE, FOUR, null},
      },
      new Number[][] {
          {FOUR, TWO, null, SIX, null, null, FIVE, null, EIGHT},
          {null, null, null, SEVEN, null, THREE, TWO, SIX, FOUR},
          {SEVEN, null, null, null, null, null, NINE, null, null},
          {null, null, null, null, null, FOUR, THREE, null, null},
          {FIVE, FOUR, ONE, null, null, null, SEVEN, EIGHT, TWO},
          {null, null, EIGHT, TWO, null, null, null, null, null},
          {null, null, SEVEN, null, null, null, null, null, NINE},
          {ONE, FIVE, FOUR, THREE, null, NINE, null, null, null},
          {TWO, null, NINE, null, null, EIGHT, null, FOUR, THREE},
      },
      new Number[][] {
          {null, null, THREE, null, null, ONE, null, null, EIGHT},
          {NINE, null, FIVE, SEVEN, EIGHT, THREE, null, null, FOUR},
          {null, EIGHT, null, FOUR, TWO, null, null, null, null},
          {null, SEVEN, TWO, EIGHT, ONE, null, THREE, null, null},
          {FIVE, null, null, null, null, null, null, null, TWO},
          {null, null, EIGHT, null, FIVE, SEVEN, FOUR, ONE, null},
          {null, null, null, null, FOUR, TWO, null, FIVE, null},
          {ONE, null, null, THREE, SIX, NINE, EIGHT, null, SEVEN},
          {TWO, null, null, FIVE, null, null, ONE, null, null},
      },
      new Number[][] {
          {TWO, null, SIX, SEVEN, null, THREE, null, FIVE, null},
          {FIVE, null, null, null, SIX, null, TWO, null, null},
          {null, null, EIGHT, ONE, null, null, FOUR, THREE, null},
          {SEVEN, null, null, null, EIGHT, null, THREE, ONE, null},
          {THREE, FOUR, null, FIVE, null, SIX, null, EIGHT, TWO},
          {null, EIGHT, TWO, null, NINE, null, null, null, FIVE},
          {null, FIVE, THREE, null, null, NINE, ONE, null, null},
          {null, null, ONE, null, SEVEN, null, null, null, THREE},
          {null, NINE, null, EIGHT, null, ONE, FIVE, null, FOUR},
      },
      new Number[][] {
          {TWO, null, null, SEVEN, FOUR, null, NINE, FIVE, EIGHT},
          {FIVE, null, null, NINE, null, null, null, null, ONE},
          {NINE, SEVEN, null, null, FIVE, null, FOUR, null, null},
          {null, null, null, TWO, EIGHT, FOUR, THREE, ONE, NINE},
          {null, FOUR, null, null, null, null, null, EIGHT, null},
          {ONE, EIGHT, TWO, THREE, NINE, SEVEN, null, null, null},
          {null, null, THREE, null, TWO, null, null, SIX, SEVEN},
          {FOUR, null, null, null, null, FIVE, null, null, THREE},
          {SIX, NINE, SEVEN, null, THREE, ONE, null, null, FOUR},
      },
      new Number[][] {
          {null, ONE, null, SEVEN, FOUR, THREE, null, null, EIGHT},
          {null, THREE, null, null, null, EIGHT, null, SEVEN, ONE},
          {null, null, EIGHT, null, null, null, null, THREE, SIX},
          {SEVEN, null, FIVE, TWO, null, null, null, null, null},
          {null, FOUR, null, null, ONE, null, null, EIGHT, null},
          {null, null, null, null, null, SEVEN, SIX, null, FIVE},
          {EIGHT, FIVE, null, null, null, null, ONE, null, null},
          {FOUR, TWO, null, SIX, null, null, null, NINE, null},
          {SIX, null, null, EIGHT, THREE, ONE, null, TWO, null},
      },
      new Number[][] {
          {null, null, SIX, null, null, THREE, NINE, null, null},
          {null, null, FOUR, null, SIX, null, TWO, SEVEN, null},
          {null, SEVEN, null, ONE, null, null, FOUR, THREE, null},
          {null, null, null, null, EIGHT, null, THREE, null, NINE},
          {null, FOUR, NINE, FIVE, null, SIX, SEVEN, EIGHT, null},
          {ONE, null, TWO, null, NINE, null, null, null, null},
          {null, FIVE, THREE, null, null, NINE, null, SIX, null},
          {null, TWO, ONE, null, SEVEN, null, EIGHT, null, null},
          {null, null, SEVEN, EIGHT, null, null, FIVE, null, null},
      },
      new Number[][] {
          {FIVE, null, TWO, SIX, null, null, NINE, null, null},
          {THREE, FOUR, null, SEVEN, null, NINE, null, null, FIVE},
          {null, NINE, null, null, null, null, EIGHT, null, null},
          {SIX, EIGHT, null, null, null, ONE, null, FOUR, null},
          {ONE, null, null, FOUR, FIVE, SIX, null, null, EIGHT},
          {null, TWO, null, EIGHT, null, null, null, FIVE, ONE},
          {null, null, FOUR, null, null, null, null, EIGHT, null},
          {TWO, null, null, THREE, null, EIGHT, null, NINE, SEVEN},
          {null, null, SEVEN, null, null, FIVE, TWO, null, SIX},
      },
      new Number[][] {
          {FIVE, ONE, TWO, SIX, null, THREE, null, SEVEN, null},
          {null, null, EIGHT, null, null, null, null, null, null},
          {null, NINE, SIX, null, null, FOUR, EIGHT, null, TWO},
          {SIX, null, null, null, THREE, null, null, FOUR, null},
          {null, null, null, null, null, null, null, null, null},
          {null, TWO, null, null, NINE, null, null, null, ONE},
          {NINE, null, FOUR, ONE, null, null, FIVE, EIGHT, null},
          {null, null, null, null, null, null, FOUR, null, null},
          {null, THREE, null, NINE, null, FIVE, TWO, ONE, SIX},
      },
      new Number[][] {
          {FIVE, null, TWO, SIX, null, null, NINE, SEVEN, FOUR},
          {THREE, null, EIGHT, null, null, NINE, null, null, FIVE},
          {SEVEN, null, SIX, null, null, null, null, null, null},
          {null, null, FIVE, TWO, null, ONE, null, null, NINE},
          {null, null, NINE, null, null, null, THREE, null, null},
          {FOUR, null, null, EIGHT, null, SEVEN, SIX, null, null},
          {null, null, null, null, null, null, FIVE, null, THREE},
          {TWO, null, null, THREE, null, null, FOUR, null, SEVEN},
          {EIGHT, THREE, SEVEN, null, null, FIVE, TWO, null, SIX},
      },
      new Number[][] {
          {FIVE, null, null, NINE, TWO, null, ONE, FOUR, null},
          {null, null, null, null, SEVEN, null, SIX, null, null},
          {EIGHT, FOUR, ONE, null, THREE, null, null, null, null},
          {null, null, null, SIX, null, TWO, THREE, NINE, EIGHT},
          {null, null, null, null, null, null, null, null, null},
          {THREE, EIGHT, NINE, ONE, null, SEVEN, null, null, null},
          {null, null, null, null, SIX, null, FOUR, TWO, SEVEN},
          {null, null, SIX, null, ONE, null, null, null, null},
          {null, SEVEN, THREE, null, EIGHT, NINE, null, null, SIX},
      },
      new Number[][] {
          {FIVE, null, SEVEN, NINE, null, EIGHT, ONE, FOUR, null},
          {null, THREE, null, FOUR, null, ONE, null, null, FIVE},
          {EIGHT, null, ONE, null, THREE, null, null, null, null},
          {null, null, null, SIX, null, null, null, NINE, null},
          {null, TWO, FOUR, EIGHT, null, THREE, SEVEN, FIVE, null},
          {null, EIGHT, null, null, null, SEVEN, null, null, null},
          {null, null, null, null, SIX, null, FOUR, null, SEVEN},
          {TWO, null, null, SEVEN, null, FOUR, null, THREE, null},
          {null, SEVEN, THREE, TWO, null, NINE, FIVE, null, SIX},
      },
      new Number[][] {
          {null, null, SEVEN, NINE, TWO, EIGHT, null, FOUR, THREE},
          {null, null, null, null, null, ONE, SIX, EIGHT, null},
          {null, null, null, FIVE, null, null, NINE, SEVEN, null},
          {null, null, null, SIX, null, TWO, THREE, NINE, null},
          {null, null, FOUR, EIGHT, null, THREE, SEVEN, null, null},
          {null, EIGHT, NINE, ONE, null, SEVEN, null, null, null},
          {null, NINE, EIGHT, null, null, FIVE, null, null, null},
          {null, FIVE, SIX, SEVEN, null, null, null, null, null},
          {FOUR, SEVEN, null, TWO, EIGHT, NINE, FIVE, null, null},
      },
      new Number[][] {
          {FIVE, null, null, null, TWO, null, null, FOUR, null},
          {null, THREE, null, FOUR, SEVEN, ONE, null, EIGHT, null},
          {EIGHT, null, null, FIVE, THREE, null, null, null, null},
          {SEVEN, null, null, null, null, null, THREE, NINE, null},
          {SIX, TWO, FOUR, EIGHT, null, THREE, SEVEN, FIVE, ONE},
          {null, EIGHT, NINE, null, null, null, null, null, FOUR},
          {null, null, null, null, SIX, FIVE, null, null, SEVEN},
          {null, FIVE, null, SEVEN, ONE, FOUR, null, THREE, null},
          {null, SEVEN, null, null, EIGHT, null, null, null, SIX},
      },
      new Number[][] {
          {FIVE, SIX, SEVEN, null, TWO, null, null, FOUR, THREE},
          {NINE, THREE, null, null, SEVEN, null, SIX, null, null},
          {EIGHT, null, ONE, FIVE, null, null, null, SEVEN, TWO},
          {SEVEN, null, null, SIX, FOUR, TWO, null, null, EIGHT},
          {null, TWO, null, EIGHT, null, THREE, null, FIVE, null},
          {THREE, null, null, ONE, FIVE, SEVEN, null, null, FOUR},
          {ONE, NINE, null, null, null, FIVE, FOUR, null, SEVEN},
          {null, null, SIX, null, ONE, null, null, THREE, NINE},
          {FOUR, SEVEN, null, null, EIGHT, null, FIVE, ONE, SIX},
      },
      new Number[][] {
          {null, null, null, null, null, NINE, ONE, SEVEN, EIGHT},
          {TWO, null, null, EIGHT, SIX, ONE, null, null, FIVE},
          {NINE, EIGHT, null, null, null, FOUR, TWO, null, SIX},
          {FIVE, SEVEN, FOUR, null, NINE, null, THREE, null, null},
          {ONE, null, null, null, null, null, null, null, NINE},
          {null, null, NINE, null, THREE, null, SEVEN, TWO, FOUR},
          {SIX, null, EIGHT, FIVE, null, null, null, NINE, THREE},
          {SEVEN, null, null, FOUR, ONE, THREE, null, null, TWO},
          {THREE, FOUR, TWO, NINE, null, null, null, null, null},
      },
      new Number[][] {
          {null, FIVE, SIX, THREE, null, NINE, ONE, null, null},
          {TWO, null, null, null, null, ONE, NINE, FOUR, FIVE},
          {null, null, ONE, null, null, FOUR, null, THREE, null},
          {FIVE, SEVEN, null, null, NINE, null, null, SIX, ONE},
          {null, null, null, null, null, null, null, null, null},
          {EIGHT, SIX, null, null, THREE, null, null, TWO, FOUR},
          {null, ONE, null, FIVE, null, null, FOUR, null, null},
          {SEVEN, NINE, FIVE, FOUR, null, null, null, null, TWO},
          {null, null, TWO, NINE, null, SIX, FIVE, ONE, null},
      },
      new Number[][] {
          {null, FIVE, SIX, null, TWO, NINE, null, SEVEN, null},
          {TWO, null, SEVEN, null, SIX, null, NINE, null, null},
          {NINE, null, ONE, SEVEN, null, null, null, THREE, null},
          {null, null, null, TWO, null, null, null, null, ONE},
          {null, TWO, null, null, FOUR, null, null, FIVE, null},
          {EIGHT, null, null, null, null, FIVE, null, null, null},
          {null, ONE, null, null, null, TWO, FOUR, null, THREE},
          {null, null, FIVE, null, ONE, null, SIX, null, TWO},
          {null, FOUR, null, NINE, EIGHT, null, FIVE, ONE, null},
      },
      new Number[][] {
          {FOUR, FIVE, SIX, null, TWO, null, null, null, null},
          {null, THREE, null, null, null, ONE, NINE, null, null},
          {null, null, null, SEVEN, FIVE, null, TWO, THREE, null},
          {FIVE, SEVEN, FOUR, null, null, null, THREE, null, null},
          {null, null, THREE, null, null, null, EIGHT, null, null},
          {null, null, NINE, null, null, null, SEVEN, TWO, FOUR},
          {null, ONE, EIGHT, null, SEVEN, TWO, null, null, null},
          {null, null, FIVE, FOUR, null, null, null, EIGHT, null},
          {null, null, null, null, EIGHT, null, FIVE, ONE, SEVEN},
      },
      new Number[][] {
          {FOUR, null, SIX, THREE, null, null, null, null, null},
          {TWO, null, null, null, SIX, null, NINE, FOUR, FIVE},
          {null, null, ONE, null, FIVE, FOUR, TWO, null, null},
          {FIVE, null, null, TWO, null, EIGHT, THREE, SIX, ONE},
          {null, TWO, THREE, SIX, null, SEVEN, EIGHT, FIVE, null},
          {EIGHT, SIX, NINE, ONE, null, FIVE, null, null, FOUR},
          {null, null, EIGHT, FIVE, SEVEN, null, FOUR, null, null},
          {SEVEN, NINE, FIVE, null, ONE, null, null, null, TWO},
          {null, null, null, null, null, SIX, FIVE, null, SEVEN},
      },
      new Number[][] {
          {SIX, null, null, null, null, null, null, null, ONE},
          {null, null, NINE, THREE, null, null, null, FOUR, SEVEN},
          {null, null, null, NINE, FOUR, TWO, SIX, null, THREE},
          {null, SIX, null, null, null, THREE, EIGHT, null, null},
          {NINE, TWO, EIGHT, null, null, null, FOUR, THREE, FIVE},
          {null, null, FIVE, TWO, null, null, null, SIX, null},
          {SEVEN, null, FOUR, EIGHT, TWO, ONE, null, null, null},
          {THREE, FIVE, null, null, null, NINE, ONE, null, null},
          {EIGHT, null, null, null, null, null, null, null, FOUR},
      },
      new Number[][] {
          {null, null, THREE, SEVEN, FIVE, null, null, null, ONE},
          {null, null, null, THREE, null, SIX, null, null, SEVEN},
          {FIVE, null, null, NINE, null, null, null, EIGHT, THREE},
          {null, SIX, null, FIVE, NINE, null, EIGHT, null, TWO},
          {NINE, null, EIGHT, null, null, null, FOUR, null, FIVE},
          {ONE, null, FIVE, null, EIGHT, FOUR, null, SIX, null},
          {SEVEN, NINE, null, null, null, ONE, null, null, SIX},
          {THREE, null, null, FOUR, null, NINE, null, null, null},
          {EIGHT, null, null, null, THREE, FIVE, NINE, null, null},
      },
      new Number[][] {
          {SIX, null, THREE, SEVEN, null, null, TWO, null, null},
          {TWO, EIGHT, null, null, null, null, FIVE, null, null},
          {null, SEVEN, null, NINE, FOUR, null, SIX, null, null},
          {FOUR, null, null, FIVE, NINE, null, EIGHT, ONE, null},
          {NINE, null, null, null, SIX, null, null, null, FIVE},
          {null, THREE, FIVE, null, EIGHT, FOUR, null, null, NINE},
          {null, null, FOUR, null, TWO, ONE, null, FIVE, null},
          {null, null, SIX, null, null, null, null, TWO, EIGHT},
          {null, null, TWO, null, null, FIVE, NINE, null, FOUR},
      },
      new Number[][] {
          {null, null, null, null, null, null, TWO, null, SEVEN},
          {null, null, null, EIGHT, FOUR, TWO, THREE, null, null},
          {null, FOUR, THREE, SEVEN, null, NINE, EIGHT, SIX, null},
          {SEVEN, THREE, null, FOUR, null, null, null, null, NINE},
          {null, null, null, NINE, SEVEN, FIVE, null, null, null},
          {ONE, null, null, null, null, THREE, null, TWO, FOUR},
          {null, SIX, NINE, TWO, null, SEVEN, FOUR, ONE, null},
          {null, null, EIGHT, THREE, SIX, FOUR, null, null, null},
          {FOUR, null, TWO, null, null, null, null, null, null},
      },
      new Number[][] {
          {null, EIGHT, ONE, null, null, SIX, null, null, SEVEN},
          {null, null, SEVEN, EIGHT, FOUR, null, THREE, NINE, null},
          {null, null, null, SEVEN, null, null, EIGHT, null, FIVE},
          {SEVEN, null, null, null, TWO, null, FIVE, null, null},
          {EIGHT, TWO, FOUR, null, null, null, ONE, THREE, SIX},
          {null, null, FIVE, null, EIGHT, null, null, null, FOUR},
          {THREE, null, NINE, null, null, SEVEN, null, null, null},
          {null, ONE, EIGHT, null, SIX, FOUR, NINE, null, null},
          {FOUR, null, null, ONE, null, null, SIX, FIVE, null},
      },
      new Number[][] {
          {null, null, ONE, FIVE, null, SIX, TWO, null, null},
          {null, FIVE, null, null, FOUR, TWO, null, NINE, null},
          {null, null, THREE, SEVEN, ONE, null, EIGHT, null, null},
          {SEVEN, null, SIX, null, TWO, null, FIVE, null, null},
          {null, TWO, null, null, null, null, null, THREE, null},
          {null, null, FIVE, null, EIGHT, null, SEVEN, null, FOUR},
          {null, null, NINE, null, FIVE, SEVEN, FOUR, null, null},
          {null, ONE, null, THREE, SIX, null, null, SEVEN, null},
          {null, null, TWO, ONE, null, EIGHT, SIX, null, null},
      },
      new Number[][] {
          {NINE, null, ONE, FIVE, null, SIX, null, null, SEVEN},
          {SIX, null, SEVEN, null, FOUR, null, THREE, null, ONE},
          {TWO, FOUR, null, SEVEN, null, null, null, SIX, FIVE},
          {null, THREE, null, FOUR, TWO, null, FIVE, null, NINE},
          {null, null, null, null, null, null, null, null, null},
          {ONE, null, FIVE, null, EIGHT, THREE, null, TWO, null},
          {THREE, SIX, null, null, null, SEVEN, null, ONE, EIGHT},
          {FIVE, null, EIGHT, null, SIX, null, NINE, null, TWO},
          {FOUR, null, null, ONE, null, EIGHT, SIX, null, THREE},
      },
      new Number[][] {
          {null, null, ONE, FIVE, THREE, SIX, null, FOUR, SEVEN},
          {SIX, null, null, null, FOUR, null, null, null, ONE},
          {TWO, null, null, null, ONE, null, EIGHT, null, null},
          {null, null, null, FOUR, null, null, FIVE, EIGHT, NINE},
          {EIGHT, null, FOUR, NINE, SEVEN, FIVE, ONE, null, SIX},
          {ONE, NINE, FIVE, null, null, THREE, null, null, null},
          {null, null, NINE, null, FIVE, null, null, null, EIGHT},
          {FIVE, null, null, null, SIX, null, null, null, TWO},
          {FOUR, SEVEN, null, ONE, NINE, EIGHT, SIX, null, null},
      },
      new Number[][] {
          {NINE, null, null, EIGHT, FIVE, THREE, null, null, FOUR},
          {null, null, null, FOUR, SIX, TWO, THREE, null, null},
          {TWO, THREE, null, null, SEVEN, null, null, null, FIVE},
          {SIX, EIGHT, null, null, null, null, null, THREE, ONE},
          {FIVE, null, SEVEN, NINE, null, ONE, SIX, null, TWO},
          {THREE, ONE, null, null, null, null, null, FOUR, NINE},
          {EIGHT, null, null, null, NINE, null, null, ONE, THREE},
          {null, null, ONE, THREE, TWO, EIGHT, null, null, null},
          {FOUR, null, null, SIX, ONE, FIVE, null, null, EIGHT},
      },
      new Number[][] {
          {null, SEVEN, SIX, EIGHT, FIVE, null, null, TWO, null},
          {ONE, null, EIGHT, FOUR, null, null, null, null, null},
          {null, THREE, FOUR, ONE, SEVEN, null, null, null, FIVE},
          {null, EIGHT, null, null, null, null, FIVE, THREE, ONE},
          {FIVE, null, SEVEN, NINE, null, ONE, SIX, null, TWO},
          {THREE, ONE, TWO, null, null, null, null, FOUR, null},
          {EIGHT, null, null, null, NINE, FOUR, TWO, ONE, null},
          {null, null, null, null, null, EIGHT, FOUR, null, SIX},
          {null, TWO, null, null, ONE, FIVE, NINE, SEVEN, null},
      },
      new Number[][] {
          {null, SEVEN, SIX, EIGHT, null, null, null, TWO, FOUR},
          {ONE, null, null, FOUR, SIX, null, THREE, null, null},
          {TWO, null, FOUR, null, null, null, null, SIX, FIVE},
          {null, EIGHT, null, null, FOUR, SEVEN, null, null, null},
          {FIVE, null, SEVEN, NINE, null, ONE, SIX, null, TWO},
          {null, null, null, FIVE, EIGHT, null, null, FOUR, null},
          {EIGHT, SIX, null, null, null, null, TWO, null, THREE},
          {null, null, ONE, null, TWO, EIGHT, null, null, SIX},
          {FOUR, TWO, null, null, null, FIVE, NINE, SEVEN, null},
      },
      new Number[][] {
          {null, SEVEN, SIX, null, FIVE, null, null, TWO, null},
          {null, null, EIGHT, FOUR, null, TWO, THREE, null, null},
          {TWO, THREE, FOUR, ONE, SEVEN, NINE, null, SIX, null},
          {null, null, null, TWO, FOUR, null, FIVE, THREE, ONE},
          {null, null, null, null, null, null, null, null, null},
          {THREE, ONE, TWO, null, EIGHT, SIX, null, null, null},
          {null, SIX, null, SEVEN, NINE, FOUR, TWO, ONE, THREE},
          {null, null, ONE, THREE, null, EIGHT, FOUR, null, null},
          {null, TWO, null, null, ONE, null, NINE, SEVEN, null},
      },
      new Number[][] {
          {null, null, SIX, EIGHT, FIVE, null, ONE, TWO, null},
          {null, FIVE, null, null, null, TWO, THREE, null, SEVEN},
          {null, THREE, FOUR, ONE, SEVEN, null, EIGHT, null, FIVE},
          {null, null, null, TWO, null, null, null, null, null},
          {null, FOUR, SEVEN, null, null, null, SIX, EIGHT, null},
          {null, null, null, null, null, SIX, null, null, null},
          {EIGHT, null, FIVE, null, NINE, FOUR, TWO, ONE, null},
          {SEVEN, null, ONE, THREE, null, null, null, FIVE, null},
          {null, TWO, THREE, null, ONE, FIVE, NINE, null, null},
      },
      new Number[][] {
          {NINE, null, null, ONE, FOUR, SEVEN, null, null, TWO},
          {ONE, null, null, null, TWO, null, SEVEN, NINE, null},
          {null, EIGHT, TWO, null, NINE, null, null, null, FIVE},
          {null, TWO, SEVEN, null, null, null, null, SIX, null},
          {null, null, null, EIGHT, null, TWO, null, null, null},
          {null, FOUR, null, null, null, null, THREE, TWO, null},
          {TWO, null, null, null, THREE, null, SIX, EIGHT, null},
          {null, ONE, SIX, null, EIGHT, null, null, null, THREE},
          {THREE, null, null, SEVEN, SIX, ONE, null, null, NINE},
      },
      new Number[][] {
          {null, SIX, FIVE, ONE, null, null, null, THREE, null},
          {ONE, null, null, null, TWO, EIGHT, SEVEN, NINE, SIX},
          {null, EIGHT, null, SIX, null, null, null, null, null},
          {null, TWO, null, THREE, ONE, null, NINE, null, null},
          {null, NINE, THREE, EIGHT, null, TWO, ONE, FIVE, null},
          {null, null, ONE, null, FIVE, SIX, null, TWO, null},
          {null, null, null, null, null, FIVE, null, EIGHT, null},
          {FOUR, ONE, SIX, TWO, EIGHT, null, null, null, THREE},
          {null, FIVE, null, null, null, ONE, TWO, FOUR, null},
      },
      new Number[][] {
          {null, null, FIVE, ONE, null, null, EIGHT, null, null},
          {null, THREE, null, null, TWO, EIGHT, null, NINE, SIX},
          {null, null, TWO, SIX, NINE, null, null, null, FIVE},
          {null, null, null, null, ONE, FOUR, null, SIX, null},
          {SIX, null, THREE, EIGHT, null, TWO, ONE, null, FOUR},
          {null, FOUR, null, NINE, FIVE, null, null, null, null},
          {TWO, null, null, null, THREE, FIVE, SIX, null, null},
          {FOUR, ONE, null, TWO, EIGHT, null, null, SEVEN, null},
          {null, null, EIGHT, null, null, ONE, TWO, null, null},
      },
      new Number[][] {
          {NINE, SIX, null, ONE, null, SEVEN, null, null, null},
          {null, THREE, FOUR, null, TWO, EIGHT, SEVEN, NINE, SIX},
          {SEVEN, null, null, null, null, THREE, null, ONE, FIVE},
          {null, TWO, null, null, ONE, null, NINE, SIX, null},
          {null, NINE, null, null, null, null, null, FIVE, null},
          {null, FOUR, ONE, null, FIVE, null, null, TWO, null},
          {TWO, SEVEN, null, FOUR, null, null, null, null, ONE},
          {FOUR, ONE, SIX, TWO, EIGHT, null, FIVE, SEVEN, null},
          {null, null, null, SEVEN, null, ONE, null, FOUR, NINE},
      },
      new Number[][] {
          {EIGHT, null, SIX, null, NINE, null, null, FOUR, null},
          {FIVE, null, null, SEVEN, FOUR, null, SIX, EIGHT, null},
          {null, SEVEN, FOUR, null, ONE, null, null, TWO, null},
          {TWO, null, SEVEN, SIX, THREE, null, null, null, EIGHT},
          {null, null, THREE, ONE, null, TWO, NINE, null, null},
          {SIX, null, null, null, SEVEN, EIGHT, TWO, null, FIVE},
          {null, SIX, null, null, TWO, null, EIGHT, FIVE, null},
          {null, FOUR, EIGHT, null, SIX, SEVEN, null, null, TWO},
          {null, TWO, null, null, EIGHT, null, SEVEN, null, FOUR},
      },
      new Number[][] {
          {EIGHT, THREE, null, TWO, null, null, null, FOUR, SEVEN},
          {FIVE, ONE, null, null, null, null, null, EIGHT, null},
          {null, null, null, EIGHT, null, SIX, null, TWO, THREE},
          {TWO, null, SEVEN, SIX, THREE, null, null, null, null},
          {FOUR, EIGHT, null, null, null, null, null, SEVEN, SIX},
          {null, null, null, null, SEVEN, EIGHT, TWO, null, FIVE},
          {SEVEN, SIX, null, THREE, null, FOUR, null, null, null},
          {null, FOUR, null, null, null, null, null, NINE, TWO},
          {THREE, TWO, null, null, null, ONE, null, SIX, FOUR},
      },
      new Number[][] {
          {null, null, null, null, null, FIVE, null, FOUR, SEVEN},
          {FIVE, null, null, SEVEN, null, THREE, null, null, NINE},
          {null, SEVEN, FOUR, EIGHT, ONE, null, null, null, THREE},
          {null, null, null, SIX, null, null, null, ONE, null},
          {null, EIGHT, null, ONE, null, TWO, null, SEVEN, null},
          {null, NINE, null, null, null, EIGHT, null, null, null},
          {SEVEN, null, null, null, TWO, FOUR, EIGHT, FIVE, null},
          {ONE, null, null, FIVE, null, SEVEN, null, null, TWO},
          {THREE, TWO, null, NINE, null, null, null, null, null},
      },
      new Number[][] {
          {null, null, null, null, null, FIVE, ONE, null, null},
          {FIVE, null, null, SEVEN, FOUR, null, SIX, null, null},
          {null, SEVEN, null, EIGHT, ONE, SIX, FIVE, null, null},
          {TWO, FIVE, SEVEN, null, null, NINE, FOUR, null, null},
          {null, EIGHT, null, null, FIVE, null, null, SEVEN, null},
          {null, null, ONE, FOUR, null, null, TWO, THREE, FIVE},
          {null, null, NINE, THREE, TWO, FOUR, null, FIVE, null},
          {null, null, EIGHT, null, SIX, SEVEN, null, null, TWO},
          {null, null, FIVE, NINE, null, null, null, null, null},
      },
      new Number[][] {
          {null, THREE, null, null, null, FIVE, ONE, null, null},
          {null, null, TWO, SEVEN, null, null, SIX, EIGHT, null},
          {null, null, null, EIGHT, ONE, null, null, TWO, null},
          {null, FIVE, SEVEN, null, THREE, null, FOUR, ONE, null},
          {null, EIGHT, THREE, ONE, null, TWO, NINE, SEVEN, null},
          {null, NINE, ONE, null, SEVEN, null, TWO, THREE, null},
          {null, SIX, null, null, TWO, FOUR, null, null, null},
          {null, FOUR, EIGHT, null, null, SEVEN, THREE, null, null},
          {null, null, FIVE, NINE, null, null, null, SIX, null},
      },
      new Number[][] {
          {null, FOUR, null, null, SEVEN, FIVE, NINE, null, null},
          {NINE, null, ONE, null, EIGHT, THREE, FIVE, FOUR, null},
          {null, null, SEVEN, FOUR, SIX, null, EIGHT, null, null},
          {SIX, THREE, null, null, FIVE, ONE, null, NINE, FOUR},
          {null, null, null, null, null, null, null, null, null},
          {FIVE, ONE, null, NINE, THREE, null, null, EIGHT, TWO},
          {null, null, FIVE, null, ONE, FOUR, TWO, null, null},
          {null, TWO, EIGHT, THREE, NINE, null, FOUR, null, FIVE},
          {null, null, SIX, FIVE, TWO, null, null, ONE, null},
      },
      new Number[][] {
          {EIGHT, FOUR, null, ONE, null, null, null, TWO, SIX},
          {NINE, null, ONE, null, null, null, FIVE, null, null},
          {null, null, null, FOUR, SIX, null, null, null, ONE},
          {null, null, TWO, EIGHT, FIVE, ONE, SEVEN, null, FOUR},
          {null, null, NINE, SIX, null, TWO, ONE, null, null},
          {FIVE, null, FOUR, NINE, THREE, SEVEN, SIX, null, null},
          {THREE, null, null, null, ONE, FOUR, null, null, null},
          {null, null, EIGHT, null, null, null, FOUR, null, FIVE},
          {FOUR, SEVEN, null, null, null, EIGHT, null, ONE, NINE},
      },
      new Number[][] {
          {null, null, THREE, ONE, null, null, null, null, null},
          {NINE, null, ONE, null, EIGHT, THREE, null, null, null},
          {TWO, FIVE, SEVEN, FOUR, SIX, null, EIGHT, null, null},
          {SIX, null, TWO, null, null, null, null, NINE, null},
          {SEVEN, EIGHT, null, null, null, null, null, FIVE, THREE},
          {null, ONE, null, null, null, null, SIX, null, TWO},
          {null, null, FIVE, null, ONE, FOUR, TWO, SIX, EIGHT},
          {null, null, null, THREE, NINE, null, FOUR, null, FIVE},
          {null, null, null, null, null, EIGHT, THREE, null, null},
      },
      new Number[][] {
          {SEVEN, FOUR, null, null, null, null, null, SIX, null},
          {null, null, null, THREE, SIX, EIGHT, null, FIVE, null},
          {null, SIX, null, null, SEVEN, null, THREE, NINE, null},
          {null, THREE, ONE, EIGHT, FIVE, null, null, SEVEN, NINE},
          {null, null, null, NINE, null, THREE, null, null, null},
          {TWO, NINE, null, null, FOUR, SEVEN, FIVE, THREE, null},
          {null, ONE, SIX, null, THREE, null, null, TWO, null},
          {null, EIGHT, null, FIVE, TWO, NINE, null, null, null},
          {null, FIVE, null, null, null, null, null, FOUR, SEVEN},
      },
      new Number[][] {
          {SEVEN, FOUR, null, TWO, NINE, null, ONE, null, null},
          {ONE, null, NINE, null, null, EIGHT, SEVEN, FIVE, null},
          {null, null, null, FOUR, null, null, null, NINE, TWO},
          {null, null, null, null, FIVE, TWO, null, null, NINE},
          {null, SEVEN, FOUR, null, null, null, TWO, EIGHT, null},
          {TWO, null, null, SIX, FOUR, null, null, null, null},
          {NINE, ONE, null, null, null, FOUR, null, null, null},
          {null, EIGHT, SEVEN, FIVE, null, null, SIX, null, THREE},
          {null, null, TWO, null, EIGHT, SIX, null, FOUR, SEVEN},
      },
      new Number[][] {
          {null, null, THREE, TWO, null, null, ONE, null, null},
          {ONE, null, null, THREE, SIX, EIGHT, null, FIVE, null},
          {null, SIX, null, null, null, ONE, null, null, TWO},
          {SIX, null, ONE, null, null, TWO, null, SEVEN, null},
          {null, SEVEN, null, NINE, ONE, THREE, null, EIGHT, null},
          {null, NINE, null, SIX, null, null, FIVE, null, ONE},
          {NINE, null, null, SEVEN, null, null, null, TWO, null},
          {null, EIGHT, null, FIVE, TWO, NINE, null, null, THREE},
          {null, null, TWO, null, null, SIX, NINE, null, null},
      },
      new Number[][] {
          {null, FOUR, null, TWO, null, null, ONE, SIX, EIGHT},
          {null, null, NINE, THREE, SIX, EIGHT, SEVEN, null, null},
          {null, SIX, null, null, null, null, null, null, TWO},
          {null, THREE, ONE, null, FIVE, null, FOUR, null, null},
          {FIVE, SEVEN, null, null, ONE, null, null, EIGHT, SIX},
          {null, null, EIGHT, null, FOUR, null, FIVE, THREE, null},
          {NINE, null, null, null, null, null, null, TWO, null},
          {null, null, SEVEN, FIVE, TWO, NINE, SIX, null, null},
          {THREE, FIVE, TWO, null, null, SIX, null, FOUR, null},
      },
      new Number[][] {
          {null, null, SIX, null, null, TWO, null, null, null},
          {null, TWO, ONE, null, FIVE, null, THREE, null, null},
          {FOUR, EIGHT, null, null, null, THREE, SIX, null, TWO},
          {null, FOUR, null, FIVE, null, null, TWO, null, ONE},
          {null, NINE, null, SIX, THREE, ONE, null, SEVEN, null},
          {EIGHT, null, SEVEN, null, null, NINE, null, SIX, null},
          {FIVE, null, TWO, NINE, null, null, null, THREE, SEVEN},
          {null, null, FOUR, null, SIX, null, ONE, TWO, null},
          {null, null, null, SEVEN, null, null, NINE, null, null},
      },
      new Number[][] {
          {null, null, SIX, EIGHT, NINE, null, SEVEN, null, FOUR},
          {null, null, null, null, null, null, null, EIGHT, NINE},
          {FOUR, null, null, ONE, SEVEN, null, SIX, FIVE, null},
          {null, null, null, FIVE, null, null, null, null, ONE},
          {TWO, null, FIVE, SIX, null, ONE, FOUR, null, EIGHT},
          {EIGHT, null, null, null, null, NINE, null, null, null},
          {null, SIX, TWO, null, ONE, FOUR, null, null, SEVEN},
          {NINE, SEVEN, null, null, null, null, null, null, null},
          {ONE, null, EIGHT, null, TWO, FIVE, NINE, null, null},
      },
      new Number[][] {
          {THREE, FIVE, SIX, null, null, TWO, null, ONE, null},
          {SEVEN, null, ONE, null, FIVE, SIX, THREE, null, null},
          {null, null, null, null, null, null, null, null, null},
          {SIX, FOUR, null, FIVE, null, SEVEN, TWO, NINE, ONE},
          {null, NINE, FIVE, null, null, null, FOUR, SEVEN, null},
          {EIGHT, ONE, SEVEN, TWO, null, NINE, null, SIX, THREE},
          {null, null, null, null, null, null, null, null, null},
          {null, null, FOUR, THREE, SIX, null, ONE, null, FIVE},
          {null, THREE, null, SEVEN, null, null, NINE, FOUR, SIX},
      },
      new Number[][] {
          {THREE, null, null, EIGHT, NINE, null, SEVEN, null, null},
          {SEVEN, TWO, ONE, FOUR, null, SIX, THREE, EIGHT, null},
          {null, EIGHT, null, ONE, null, null, null, null, TWO},
          {SIX, FOUR, null, FIVE, EIGHT, null, null, null, null},
          {null, NINE, null, null, THREE, null, null, SEVEN, null},
          {null, null, null, null, FOUR, NINE, null, SIX, THREE},
          {FIVE, null, null, null, null, FOUR, null, THREE, null},
          {null, SEVEN, FOUR, THREE, null, EIGHT, ONE, TWO, FIVE},
          {null, null, EIGHT, null, TWO, FIVE, null, null, SIX},
      },
      new Number[][] {
          {ONE, EIGHT, null, null, THREE, SIX, null, null, null},
          {FOUR, null, null, null, null, null, THREE, FIVE, null},
          {null, SIX, null, null, FOUR, SEVEN, EIGHT, ONE, TWO},
          {TWO, null, ONE, NINE, null, null, null, EIGHT, null},
          {FIVE, null, null, null, null, null, null, null, ONE},
          {null, FOUR, null, null, null, ONE, SIX, null, THREE},
          {SEVEN, ONE, TWO, THREE, NINE, null, null, SIX, null},
          {null, NINE, EIGHT, null, null, null, null, null, FIVE},
          {null, null, null, SIX, EIGHT, null, null, SEVEN, NINE},
      },
      new Number[][] {
          {ONE, null, null, TWO, THREE, SIX, NINE, null, null},
          {null, null, null, null, null, null, THREE, FIVE, null},
          {null, SIX, null, FIVE, FOUR, null, EIGHT, null, null},
          {null, null, ONE, NINE, SIX, null, null, null, FOUR},
          {FIVE, null, null, null, null, null, null, null, ONE},
          {EIGHT, null, null, null, FIVE, ONE, SIX, null, null},
          {null, null, TWO, null, NINE, FIVE, null, SIX, null},
          {null, NINE, EIGHT, null, null, null, null, null, null},
          {null, null, FOUR, SIX, EIGHT, TWO, null, null, NINE},
      },
      new Number[][] {
          {ONE, null, null, null, THREE, SIX, null, FOUR, SEVEN},
          {null, TWO, null, null, null, null, THREE, null, SIX},
          {null, null, null, FIVE, FOUR, null, EIGHT, null, null},
          {null, null, ONE, null, null, THREE, FIVE, EIGHT, FOUR},
          {null, null, SIX, FOUR, null, EIGHT, SEVEN, null, null},
          {EIGHT, FOUR, NINE, SEVEN, null, null, SIX, null, null},
          {null, null, TWO, null, NINE, FIVE, null, null, null},
          {SIX, null, EIGHT, null, null, null, null, THREE, null},
          {THREE, FIVE, null, SIX, EIGHT, null, null, null, NINE},
      },
      new Number[][] {
          {null, null, null, TWO, THREE, null, null, FOUR, null},
          {null, null, null, null, null, NINE, null, null, null},
          {NINE, SIX, THREE, FIVE, FOUR, null, EIGHT, null, TWO},
          {TWO, null, null, null, null, THREE, FIVE, EIGHT, null},
          {null, THREE, SIX, FOUR, null, EIGHT, SEVEN, NINE, null},
          {null, FOUR, NINE, SEVEN, null, null, null, null, THREE},
          {SEVEN, null, TWO, null, NINE, FIVE, FOUR, SIX, EIGHT},
          {null, null, null, ONE, null, null, null, null, null},
          {null, FIVE, null, null, EIGHT, TWO, null, null, null},
      },
      new Number[][] {
          {null, null, FIVE, TWO, null, null, null, null, SEVEN},
          {null, null, null, null, null, NINE, THREE, FIVE, null},
          {NINE, null, THREE, FIVE, FOUR, null, null, ONE, TWO},
          {null, null, null, NINE, SIX, THREE, FIVE, null, FOUR},
          {FIVE, THREE, null, null, null, null, null, NINE, ONE},
          {EIGHT, null, NINE, SEVEN, FIVE, ONE, null, null, null},
          {SEVEN, ONE, null, null, NINE, FIVE, FOUR, null, EIGHT},
          {null, NINE, EIGHT, ONE, null, null, null, null, null},
          {THREE, null, null, null, null, TWO, ONE, null, null},
      },
      new Number[][] {
          {SEVEN, null, null, null, null, null, TWO, FIVE, null},
          {EIGHT, FIVE, null, null, null, SEVEN, null, THREE, null},
          {null, null, FOUR, EIGHT, null, TWO, null, null, SEVEN},
          {null, ONE, null, NINE, SEVEN, null, SIX, EIGHT, TWO},
          {null, FOUR, null, null, TWO, null, null, ONE, null},
          {TWO, EIGHT, SIX, null, THREE, ONE, null, FOUR, null},
          {SIX, null, null, TWO, null, NINE, EIGHT, null, null},
          {null, TWO, null, SEVEN, null, null, null, SIX, THREE},
          {null, SEVEN, NINE, null, null, null, null, null, FOUR},
      },
      new Number[][] {
          {null, NINE, ONE, null, null, THREE, null, FIVE, null},
          {EIGHT, null, TWO, null, null, null, null, null, null},
          {null, null, FOUR, EIGHT, FIVE, null, ONE, null, SEVEN},
          {FIVE, null, null, NINE, null, null, SIX, EIGHT, null},
          {null, null, SEVEN, SIX, null, EIGHT, THREE, null, null},
          {null, EIGHT, SIX, null, null, ONE, null, null, NINE},
          {SIX, null, FIVE, null, FOUR, NINE, EIGHT, null, null},
          {null, null, null, null, null, null, NINE, null, THREE},
          {null, SEVEN, null, THREE, null, null, FIVE, TWO, null},
      },
      new Number[][] {
          {null, null, ONE, FOUR, null, null, null, FIVE, EIGHT},
          {EIGHT, null, TWO, ONE, null, null, null, null, SIX},
          {null, null, FOUR, null, FIVE, TWO, ONE, null, SEVEN},
          {FIVE, null, null, null, SEVEN, FOUR, null, null, null},
          {null, FOUR, SEVEN, SIX, null, EIGHT, THREE, ONE, null},
          {null, null, null, FIVE, THREE, null, null, null, NINE},
          {SIX, null, FIVE, TWO, FOUR, null, EIGHT, null, null},
          {FOUR, null, null, null, null, FIVE, NINE, null, THREE},
          {ONE, SEVEN, null, null, null, SIX, FIVE, null, null},
      },
      new Number[][] {
          {null, NINE, null, FOUR, SIX, null, null, null, EIGHT},
          {EIGHT, FIVE, TWO, null, NINE, SEVEN, null, THREE, null},
          {null, null, null, null, null, TWO, null, NINE, SEVEN},
          {null, ONE, null, NINE, null, null, SIX, EIGHT, TWO},
          {null, FOUR, SEVEN, null, null, null, THREE, ONE, null},
          {TWO, EIGHT, SIX, null, null, ONE, null, FOUR, null},
          {SIX, THREE, null, TWO, null, null, null, null, null},
          {null, TWO, null, SEVEN, ONE, null, NINE, SIX, THREE},
          {ONE, null, null, null, EIGHT, SIX, null, TWO, null},
      },
      new Number[][] {
          {null, NINE, ONE, FOUR, null, THREE, null, FIVE, EIGHT},
          {null, null, null, null, NINE, null, FOUR, null, SIX},
          {null, SIX, null, EIGHT, null, null, ONE, null, SEVEN},
          {null, null, null, NINE, SEVEN, FOUR, null, EIGHT, TWO},
          {null, null, SEVEN, null, null, null, THREE, null, null},
          {TWO, EIGHT, null, FIVE, THREE, ONE, null, null, null},
          {SIX, null, FIVE, null, null, NINE, null, SEVEN, null},
          {FOUR, null, EIGHT, null, ONE, null, null, null, null},
          {ONE, SEVEN, null, THREE, null, SIX, FIVE, TWO, null},
      },
      new Number[][] {
          {EIGHT, SEVEN, TWO, null, null, null, null, THREE, null},
          {null, null, SIX, null, null, THREE, null, null, TWO},
          {null, FOUR, null, ONE, null, SIX, NINE, SEVEN, null},
          {null, null, null, null, null, null, SEVEN, EIGHT, SIX},
          {null, null, null, TWO, SIX, ONE, null, null, null},
          {FOUR, SIX, THREE, null, null, null, null, null, null},
          {null, EIGHT, SEVEN, FOUR, null, NINE, null, ONE, null},
          {ONE, null, null, SIX, null, null, EIGHT, null, null},
          {null, TWO, null, null, null, null, FOUR, SIX, SEVEN},
      },
      new Number[][] {
          {EIGHT, null, TWO, NINE, null, FIVE, null, THREE, null},
          {NINE, null, SIX, null, null, THREE, null, null, TWO},
          {THREE, FOUR, null, null, TWO, SIX, null, null, null},
          {null, null, ONE, null, THREE, null, SEVEN, EIGHT, SIX},
          {SEVEN, FIVE, EIGHT, null, null, null, THREE, NINE, FOUR},
          {FOUR, SIX, THREE, null, NINE, null, ONE, null, null},
          {null, null, null, FOUR, FIVE, null, null, ONE, THREE},
          {ONE, null, null, SIX, null, null, EIGHT, null, NINE},
          {null, TWO, null, THREE, null, EIGHT, FOUR, null, SEVEN},
      },
      new Number[][] {
          {null, SEVEN, TWO, null, null, null, null, null, null},
          {NINE, ONE, SIX, null, EIGHT, null, null, null, null},
          {THREE, FOUR, FIVE, null, TWO, null, null, SEVEN, null},
          {null, NINE, null, FIVE, null, FOUR, null, EIGHT, SIX},
          {null, null, EIGHT, TWO, null, ONE, THREE, null, null},
          {FOUR, SIX, null, EIGHT, null, SEVEN, null, TWO, null},
          {null, EIGHT, null, null, FIVE, null, TWO, ONE, THREE},
          {null, null, null, null, SEVEN, null, EIGHT, FIVE, NINE},
          {null, null, null, null, null, null, FOUR, SIX, null},
      },
  });
}
